@AuthenticationServer_HostAddress = http://localhost:5144

### Login
POST {{AuthenticationServer_HostAddress}}/auth/login
Content-Type: application/json

{
  "username": "testuser",
  "password": "testpassword"
}

### Register
POST {{AuthenticationServer_HostAddress}}/auth/register
Content-Type: application/json

{
  "username": "testuser",
  "password": "testpassword"
}

